#ifndef __INC_SERVICE_H__
#define __INC_SERVICE_H__

#define ENABLE_AUTODETECT_INTERNAL_IP
#define ENABLE_PROXY_IP
#define ENABLE_PORT_SECURITY
#define _IMPROVED_PACKET_ENCRYPTION_ // 패킷 암호화 개선
//#define __AUCTION__
#define __PET_SYSTEM__
#define __UDP_BLOCK__
#endif

#define __WEAPON_COSTUME_SYSTEM__
#define ADVANCED_BLOCK_DODGE
//#define ADVANCED_MOB_ENCHANT
//#define ADVANCED_MOB_RESIST

//#define ENABLE_COSTUME_MOUNT
//#define ENABLE_PET_SLOT
//#define ENABLE_MOUNT_LIKE_HORSE
//#define ENABLE_RENEVAL_REGEN
#define ENABLE_BOSS_NO_FALLBACK

#define ENABLE_SAMA_FIXS
//#define ENABLE_RARITY_SYSTEM